import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";

const pretendard = localFont({
  src: "../assets/fonts/woff2/PretendardVariable.woff2",
});

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body className={pretendard.className}>
        <main
          style={{
            display: "flex",
            flexDirection: "column",
            overflow: "auto",
            minHeight: "100dvh",
            maxWidth: "440px",
            margin: "0 auto",
            outline: "1px solid black",
          }}
        >
          {children}
        </main>
      </body>
    </html>
  );
}
